gui:
  theme:
    activeBorderColor:
      - "#efb080" # orange1 – Border color of focused window
      - "bold"
    inactiveBorderColor:
      - "#3b3b3b" # gray3 – Border color of non-focused windows
    searchingActiveBorderColor:
      - "#af9cff" # cyan1 – Border color of focused window when searching in that window
      - "bold"
    optionsTextColor:
      - "#c1808a" # yellow2 – Color of keybindings help text in the bottom line
    selectedLineBgColor:
      - "#383838" # gray2 – Background color of selected line
    inactiveViewSelectedLineBgColor:
      - "#1d1d1d" # gray1 – Background color of selected line when view doesn't have focus
    cherryPickedCommitFgColor:
      - "#aa9bf5" # purple0 – Foreground color of copied commit
    cherryPickedCommitBgColor:
      - "#af9cff" # gray3 – Background color of copied commit
    markedBaseCommitFgColor:
      - "#228df2" # blue1 – Foreground color of marked base commit (for rebase)
    markedBaseCommitBgColor:
      - "#f8c762" # yellow1 – Background color of marked base commit (for rebase)
    unstagedChangesColor:
      - "#c1808a" # red – Color for file with unstaged changes
    defaultFgColor:
      - "#d6d6dd" # gray4 – Default text color

  authorColors:
    "*": "#15ac91" # rose – Author color
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    # pager: delta --paging=never # brew install git-delta
